#ifndef __FAT_STANDARD_H
#define __FAT_STANDARD_H

#define FAT_FILENAME_LENGTH							11
#define FAT_SMALLEST_LEGAL_CLUSTER_NUMBER			2

typedef enum {
	FAT_FILESYSTEM_TYPE_INVALID,
	FAT_FILESYSTEM_TYPE_FAT12,
	FAT_FILESYSTEM_TYPE_FAT16,
	FAT_FILESYSTEM_TYPE_FAT32	
} fatFilesystemType_e;

#endif	// __FAT_STANDARD_H
